export const addItem = val => ({ type: 'ADD_ITEM', val });
export const delItem = val => ({ type: 'DEL_ITEM', val });
export const editItem = val => ({ type: 'EDIT_ITEM', val });
export const searchNothing = () => ({ type: 'SEARCH_NOTHING' });
export const searchResult = val => ({ type: 'SEARCH_RESULT', val });
export const sortState = () => ({ type: 'SORT_STATE' });
export const sortAnchor = val => ({ type: 'SORT_ANCHOR', val });
export const sortingBy = val => ({ type: 'SORT_BY', val });
export const sortingName = val => ({ type: 'SORT_NAME', val });
export const sortingDate = val => ({ type: 'SORT_DATE', val });
export const resetInput = () => ({ type: 'INPUT_RESET' });
export const isChangeInput = val => ({ type: 'INPUT_TARGET', val });
export const errorAddNoSpace = () => ({ type: 'ERROR_ADD_NO_SPACE' });
export const errorAddNoRepeat = () => ({ type: 'ERROR_ADD_NO_REPEAT' });
export const errorNormal = () => ({ type: 'ERROR_NORMAL' });
export const errorInputNoSpace = () => ({ type: 'ERROR_INPUT_NO_SPACE' });
export const errorInputNoRepeat = () => ({ type: 'ERROR_INPUT_NO_REPEAT' });
export const editInput = val => ({ type: 'INPUT_EDITING', val });
export const isChecked = val => ({ type: 'CHECKED', val });
